<?php
require_once "Database.php";

class Store extends Database
{

  public function createAccount($username, $password)
  {
    $sql = "INSERT INTO accounts(username, password) VALUES('$username', '$password')";

    $result = $this->conn->query($sql);
    //$this->conn->query($sql) ~~ will execute the SQL statement;

    if ($result == false) {
      die("CANNOT ADD ACCOUNTS: " . $this->conn->error);
    } else {
      return true;
    }
  }

  public function createUser($first_name, $last_name, $address, $email, $contact_number)
  {
    $user_account_id = $this->conn->insert_id;
    //$this-conn-insert_id ~~ get the last sued id generated by the last query.

    $sql = "INSERT INTO users(first_name, last_name, address,email, contact_number, account_id) VALUES ('$first_name', '$last_name', '$address', '$email','$contact_number', '$user_account_id')";

    if ($this->conn->query($sql)) {
      header("Location:login.php");
    } else {
      die("CANNOT ADD USER: " . $this->conn->error);
    }
  }
  public function login($username, $password)
  {
    $sql = "SELECT * FROM accounts INNER JOIN users ON users.account_id = accounts.account_id WHERE accounts.username = '$username' AND accounts.password='$password' ";

    $result = $this->conn->query($sql);

    if ($result->num_rows == 1) {
      $row = $result->fetch_assoc();
      $_SESSION['user_id'] = $row['user_id'];
      $_SESSION['username'] = $row['username'];
      $_SESSION['first_name'] = $row['first_name'];
      $_SESSION['last_name'] = $row['last_name'];
      $_SESSION['status'] = $row['status'];

      header("Location:storeUI.php");
      
    } else {
      return "Invalid Credentials";
    }
  }
  public function add_item($item_name,$Price,$description){
    $sql = "INSERT INTO products(product_name, price, description) VALUES('$item_name','$Price','$description')";

    if($this->conn->query($sql)){
      header("Location:adminUI.php");
    }else{
      die("CANNOT ADD USER: " . $this->conn->error);
    }
  }
  public function get_items(){
    $sql = "SELECT * FROM products";
    $result = $this->conn->query($sql);
    if($result->num_rows>0){
      $container = array();
      while($row = $result->fetch_assoc()){
        $container[] = $row;
      }
      return $container;
    }else{
      return false;
    }
  }
   public function add_to_cart($product_name,$product_price,$user_id){
     $sql = "INSERT INTO cart(product_name,product_price,user_id) VALUES ('$product_name','$product_price','$user_id')";

     if($this->conn->query($sql)){
      header("Location:cart.php");
      echo "<div class = 'alert alert-success'>Added to cart Successfully</div>";
     }else{
       die("CANNOT ADD USER: " .$this->conn->error);
     }
   }
   public function see_cart(){
    $sql = "SELECT * FROM cart";
    $result = $this->conn->query($sql);
    if($result->num_rows>0){
      $container = array();
      while($row = $result->fetch_assoc()){
        $container[] = $row;
      }
      return $container;
    }else{
      return false;
    }
   }
  
}
